networkmap:Apartment Game Flat main
	g++ Apartment.o Game.o Flat.o main.o -o networkmap
Apartment:
	g++ -std=c++11 -c Apartment.cpp -o Apartment.o 
Game:
	g++ -std=c++11 -c Game.cpp -o Game.o 
Flat:
	g++ -std=c++11 -c Flat.cpp -o Flat.o 
main:
	g++ -std=c++11 -c main.cpp -o main.o